/* Portable regression fixtures for the human-readable BOOTCHAIN.TXT contract. */

#include "boot_report.h"

#include <stdio.h>
#include <string.h>

static void init_info(boot_chain_info_t *info)
{
    memset(info, 0, sizeof(*info));
    info->skip_hdd[0] = -1;
    info->skip_hdd[1] = -1;
    info->skip_hdd[2] = -1;
    info->payload_read_result = -1;
    info->payload_kelf_result = -1;
    info->sysconf_mount_result = -6;
    info->system_mount_result = -7;
}

static int contains(const char *text, const char *needle)
{
    return strstr(text, needle) != NULL;
}

static int test_disabled_golden_report(void)
{
    static const char expected[] =
        "PS2 HDD BOOT CHAIN REPORT\n"
        "Generated by PS2 HDD Bootstrap Manager v0.4.0-dev\n\n"
        "CONSOLE\n"
        "ROMVER: 0220JC20060905\n"
        "Expected regional system folder: BIEXEC-SYSTEM\n\n"
        "APA MBR\n"
        "Header validation: valid\n"
        "osdStart: 0x00000000\n"
        "osdSize:  0x00000000 sectors\n"
        "Pointer state: disabled\n\n"
        "ACTIVE PAYLOAD\n"
        "State: not read because the bootstrap pointer is disabled\n"
        "Probable family: No active payload\n"
        "Confidence: certain\n"
        "Probable next stage: none\n"
        "Identification method: KELF structure plus downstream filesystem evidence. Encrypted payload identity is not claimed from plaintext strings.\n\n"
        "FMCB CONFIGURATION\n"
        "mc0:/SYS-CONF/FREEMCB.CNF -> Skip_HDD: file not found\n"
        "mc1:/SYS-CONF/FREEMCB.CNF -> Skip_HDD: file not found\n"
        "mass:/FREEMCB.CNF -> Skip_HDD: file not found\n"
        "\nMEMORY-CARD HDD MODULES\n"
        "mc0: 0 module file(s) detected\n"
        "mc1: 0 module file(s) detected\n"
        "\nDOWNSTREAM HDD EVIDENCE\n"
        "__sysconf mount result: -6\n"
        "__system mount result: -7\n"
        "FHDB FREEHDB.CNF: not found\n"
        "FHDB BOOT.ELF: not found\n"
        "FHDB LK_Auto target: unavailable\n"
        "OSDMBR.CNF: not found\n"
        "OSDMBR boot_auto target: unavailable\n"
        "OSDMBR boot_auto value: unavailable\n"
        "PSBBN osdboot.elf: not found\n"
        "PSBBN characteristic partitions: 0/8\n"
        "HOSDMenu executable: not found\n"
        "HDD-OSD osd100 executable: not found\n"
        "Legacy osdmain.elf: not found\n\n"
        "ASSESSMENT\n"
        "No structural contradiction was found in the observed boot chain.\n";
    boot_chain_info_t info;
    char report[BOOT_REPORT_SIZE];
    unsigned int length;

    init_info(&info);
    snprintf(info.romver, sizeof(info.romver), "%s", "0220JC20060905");
    snprintf(info.expected_system_folder, sizeof(info.expected_system_folder),
             "%s", "BIEXEC-SYSTEM");
    snprintf(info.family, sizeof(info.family), "%s", "No active payload");
    snprintf(info.confidence, sizeof(info.confidence), "%s", "certain");
    snprintf(info.next_stage, sizeof(info.next_stage), "%s", "none");
    info.pointer_consistent = 1;

    length = boot_report_render(report, sizeof(report), &info, 0, 0,
                                "PS2 HDD Bootstrap Manager", "0.4.0-dev");
    return length == strlen(expected) && strcmp(report, expected) == 0;
}

static int test_active_evidence_and_hashes(void)
{
    boot_chain_info_t info;
    char report[BOOT_REPORT_SIZE];

    init_info(&info);
    snprintf(info.romver, sizeof(info.romver), "%s", "0220JC20060905");
    snprintf(info.expected_system_folder, sizeof(info.expected_system_folder),
             "%s", "BIEXEC-SYSTEM");
    snprintf(info.family, sizeof(info.family), "%s", "PSBBN / OSDMenu MBR");
    snprintf(info.confidence, sizeof(info.confidence), "%s", "high");
    snprintf(info.next_stage, sizeof(info.next_stage), "%s",
             "hdd0:__system:pfs:/p2lboot/osdboot.elf");
    info.pointer_consistent = 1;
    info.payload_read_result = 0;
    info.payload_kelf_result = 0;
    info.payload_bytes = 2048;
    info.kelf_file_bytes = 1800;
    memset(info.payload_sha256, 0x11, sizeof(info.payload_sha256));
    memset(info.kelf_sha256, 0x22, sizeof(info.kelf_sha256));
    info.skip_hdd[0] = 1;
    info.mc_module_count[0] = 1;
    info.mc_folder_mask[0] = 1u;
    info.mc_folder_module_mask[0][0] = 1u;
    info.osdmenu_mbr_config = 1;
    info.osdmenu_auto_target = BOOT_AUTO_PSBBN;
    snprintf(info.osdmenu_auto_path, sizeof(info.osdmenu_auto_path),
             "%s", "$PSBBN");
    info.psbbn_boot = 1;
    info.psbbn_partition_count = 8;

    boot_report_render(report, sizeof(report), &info, 0x2000u, 4u,
                       "PS2 HDD Bootstrap Manager", "0.4.0-dev");
    return contains(report, "osdStart: 0x00002000\n") &&
           contains(report, "Pointer state: enabled and consistent\n") &&
           contains(report, "Sector image bytes: 2048\n") &&
           contains(report,
                    "Sector-image SHA-256: 1111111111111111111111111111111111111111111111111111111111111111\n") &&
           contains(report,
                    "Unpadded KELF SHA-256: 2222222222222222222222222222222222222222222222222222222222222222\n") &&
           contains(report, "OSDMBR boot_auto target: $PSBBN\n") &&
           contains(report, "PSBBN characteristic partitions: 8/8\n") &&
           contains(report, "  folder: BIEXEC-SYSTEM\n    hddload.irx\n") &&
           contains(report,
                    "NOTE: External HDD modules are present. Some FMCB setups can load the HDD even when Skip_HDD is ON.");
}

static int test_assessment_branches(void)
{
    boot_chain_info_t info;
    char report[BOOT_REPORT_SIZE];

    init_info(&info);
    snprintf(info.family, sizeof(info.family), "%s", "fixture");
    snprintf(info.confidence, sizeof(info.confidence), "%s", "fixture");
    snprintf(info.next_stage, sizeof(info.next_stage), "%s", "fixture");

    info.pointer_consistent = 0;
    boot_report_render(report, sizeof(report), &info, 0x2000u, 0,
                       "test", "1");
    if (!contains(report, "CRITICAL: osdStart/osdSize are inconsistent."))
        return 0;

    info.pointer_consistent = 1;
    info.payload_read_result = -123;
    boot_report_render(report, sizeof(report), &info, 0x2000u, 4u,
                       "test", "1");
    if (!contains(report,
                  "CRITICAL: The ROM pointer is enabled but the referenced payload could not be read safely."))
        return 0;

    info.payload_read_result = 0;
    info.payload_kelf_result = -4;
    boot_report_render(report, sizeof(report), &info, 0x2000u, 4u,
                       "test", "1");
    if (!contains(report,
                  "WARNING: The active sector image does not contain a structurally valid KELF at its beginning."))
        return 0;

    info.payload_kelf_result = 0;
    boot_report_render(report, sizeof(report), &info, 0x2000u, 4u,
                       "test", "1");
    return contains(report,
                    "WARNING: A valid-looking active payload exists, but no recognized downstream environment was found.");
}

static int test_bounded_output(void)
{
    boot_chain_info_t info;
    char tiny[32];
    unsigned int length;

    init_info(&info);
    info.pointer_consistent = 1;
    snprintf(info.family, sizeof(info.family), "%s", "No active payload");
    snprintf(info.confidence, sizeof(info.confidence), "%s", "certain");
    snprintf(info.next_stage, sizeof(info.next_stage), "%s", "none");

    memset(tiny, 0x7f, sizeof(tiny));
    length = boot_report_render(tiny, sizeof(tiny), &info, 0, 0,
                                "PS2 HDD Bootstrap Manager", "0.4.0-dev");
    if (length != sizeof(tiny) - 1u || tiny[sizeof(tiny) - 1u] != '\0')
        return 0;
    if (strncmp(tiny, "PS2 HDD BOOT CHAIN REPORT", 25) != 0)
        return 0;

    return boot_report_render(NULL, 0, &info, 0, 0, "test", "1") == 0;
}

int main(void)
{
    if (!test_disabled_golden_report()) {
        fprintf(stderr, "Disabled boot report golden fixture failed.\n");
        return 1;
    }
    if (!test_active_evidence_and_hashes()) {
        fprintf(stderr, "Active boot report evidence fixture failed.\n");
        return 2;
    }
    if (!test_assessment_branches()) {
        fprintf(stderr, "Boot report assessment fixture failed.\n");
        return 3;
    }
    if (!test_bounded_output()) {
        fprintf(stderr, "Boot report bounded-output fixture failed.\n");
        return 4;
    }

    puts("All boot report tests passed.");
    return 0;
}
