#!/usr/bin/env python3
"""Generate compact printable-ASCII C tables from pinned Spleen BDF files."""

from __future__ import annotations

import argparse
import gzip
from pathlib import Path

FIRST = 32
LAST = 126
REVISION = "57f9219328c9f5873085320fe8bc8f7dd34b8791"


def parse_bdf(path: Path, width: int, height: int) -> dict[int, list[int]]:
    glyphs: dict[int, list[int]] = {}
    encoding: int | None = None
    bitmap: list[int] | None = None

    if path.suffix == ".gz":
        source_text = gzip.open(path, "rt", encoding="ascii").read()
    else:
        source_text = path.read_text(encoding="ascii")

    for raw_line in source_text.splitlines():
        line = raw_line.strip()
        if line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line == "BITMAP":
            bitmap = []
        elif line == "ENDCHAR":
            if encoding is not None and FIRST <= encoding <= LAST:
                if bitmap is None or len(bitmap) != height:
                    raise ValueError(f"{path}: encoding {encoding} has invalid height")
                if any(value >= (1 << 8) for value in bitmap):
                    raise ValueError(f"{path}: encoding {encoding} exceeds one byte")
                glyphs[encoding] = bitmap
            encoding = None
            bitmap = None
        elif bitmap is not None:
            bitmap.append(int(line, 16))

    missing = [code for code in range(FIRST, LAST + 1) if code not in glyphs]
    if missing:
        raise ValueError(f"{path}: missing printable ASCII encodings: {missing}")

    unused_mask = (1 << (8 - width)) - 1
    if any(value & unused_mask for rows in glyphs.values() for value in rows):
        raise ValueError(f"{path}: glyph pixels extend beyond declared width {width}")
    return glyphs


def emit_array(name: str, glyphs: dict[int, list[int]], height: int) -> str:
    lines = [f"const unsigned char {name}[SPLEEN_ASCII_COUNT * {height}u] = {{"]
    for code in range(FIRST, LAST + 1):
        values = ", ".join(f"0x{value:02x}" for value in glyphs[code])
        printable = chr(code).replace("\\", "backslash").replace("'", "apostrophe")
        lines.append(f"    {values}, /* {code:3d} {printable} */")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font-5x8", type=Path, required=True)
    parser.add_argument("--font-8x16", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    five = parse_bdf(args.font_5x8, 5, 8)
    eight = parse_bdf(args.font_8x16, 8, 16)
    source = f"""/* Generated by tools/generate_spleen_font.py.
 * Source: Spleen 2.2.0, commit {REVISION}
 * License: BSD-2-Clause; see third_party/spleen/LICENSE.
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include \"spleen_font_data.h\"

{emit_array("spleen_5x8_ascii", five, 8)}

{emit_array("spleen_8x16_ascii", eight, 16)}
"""
    args.output.write_text(source, encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
