/*
 * Portable BOOTCHAIN.TXT rendering.
 *
 * Evidence gathering is intentionally kept elsewhere: boot_chain_ps2.c reads
 * memory cards and PFS, while main.c still owns raw active-payload acquisition.
 * This module only turns a completed boot_chain_info_t snapshot plus the APA
 * pointer into bounded human-readable text. Keeping formatting pure makes the
 * diagnostic contract testable on a host without pretending that file saving
 * or raw HDD access is equally portable.
 */

#include "boot_report.h"
#include "sha256.h"

#include <stdarg.h>
#include <stdio.h>

/* Append formatted text while preserving a trailing NUL on truncation. */
static void report_append(char *buffer, unsigned int capacity,
                          unsigned int *length, const char *format, ...)
{
    va_list arguments;
    int written;

    if (*length >= capacity - 1u)
        return;

    va_start(arguments, format);
    written = vsnprintf(buffer + *length, capacity - *length,
                        format, arguments);
    va_end(arguments);
    if (written < 0)
        return;

    if ((unsigned int)written >= capacity - *length)
        *length = capacity - 1u;
    else
        *length += (unsigned int)written;
}

unsigned int boot_report_render(char *buffer, unsigned int capacity,
                                const boot_chain_info_t *info,
                                unsigned int start, unsigned int sectors,
                                const char *application_name,
                                const char *application_version)
{
    static const char *const folders[] = {
        "BIEXEC-SYSTEM", "BAEXEC-SYSTEM",
        "BEEXEC-SYSTEM", "BCEXEC-SYSTEM"
    };
    static const char *const modules[] = {
        "hddload.irx", "dev9.irx", "atad.irx"
    };
    static const char *const config_names[] = {
        "mc0:/SYS-CONF/FREEMCB.CNF",
        "mc1:/SYS-CONF/FREEMCB.CNF",
        "mass:/FREEMCB.CNF"
    };
    char payload_hash[65];
    char kelf_hash[65];
    unsigned int length = 0;
    unsigned int port;
    unsigned int i;

    if (buffer == NULL || capacity == 0 || info == NULL ||
        application_name == NULL || application_version == NULL)
        return 0;

    buffer[0] = '\0';
    sha256_hex(info->payload_sha256, payload_hash);
    sha256_hex(info->kelf_sha256, kelf_hash);

    report_append(buffer, capacity, &length,
                  "PS2 HDD BOOT CHAIN REPORT\n"
                  "Generated by %s v%s\n\n",
                  application_name, application_version);
    report_append(buffer, capacity, &length,
                  "CONSOLE\n"
                  "ROMVER: %s\n"
                  "Expected regional system folder: %s\n\n",
                  info->romver[0] != '\0' ? info->romver : "unavailable",
                  info->expected_system_folder);
    report_append(buffer, capacity, &length,
                  "APA MBR\n"
                  "Header validation: valid\n"
                  "osdStart: 0x%08x\n"
                  "osdSize:  0x%08x sectors\n"
                  "Pointer state: %s\n\n",
                  start, sectors,
                  info->pointer_consistent ?
                      (start == 0 ? "disabled" : "enabled and consistent") :
                      "INCONSISTENT (only one field is zero)");

    report_append(buffer, capacity, &length, "ACTIVE PAYLOAD\n");
    if (start == 0 && sectors == 0) {
        report_append(buffer, capacity, &length,
                      "State: not read because the bootstrap pointer is "
                      "disabled\n");
    } else {
        report_append(buffer, capacity, &length,
                      "Read result: %d\n"
                      "Sector image bytes: %u\n"
                      "KELF validation result: %d\n"
                      "Unpadded KELF bytes: %u\n",
                      info->payload_read_result, info->payload_bytes,
                      info->payload_kelf_result, info->kelf_file_bytes);
        if (info->payload_read_result == 0)
            report_append(buffer, capacity, &length,
                          "Sector-image SHA-256: %s\n", payload_hash);
        if (info->payload_kelf_result == 0)
            report_append(buffer, capacity, &length,
                          "Unpadded KELF SHA-256: %s\n", kelf_hash);
    }
    report_append(buffer, capacity, &length,
                  "Probable family: %s\n"
                  "Confidence: %s\n"
                  "Probable next stage: %s\n"
                  "Identification method: KELF structure plus downstream "
                  "filesystem evidence. Encrypted payload identity is not "
                  "claimed from plaintext strings.\n\n",
                  info->family, info->confidence, info->next_stage);

    report_append(buffer, capacity, &length, "FMCB CONFIGURATION\n");
    for (i = 0; i < 3; i++) {
        const char *state = info->skip_hdd[i] == 1 ? "ON" :
                            info->skip_hdd[i] == 0 ? "OFF" :
                            info->skip_hdd[i] == -1 ? "file not found" :
                                                     "setting unavailable";

        report_append(buffer, capacity, &length,
                      "%s -> Skip_HDD: %s\n", config_names[i], state);
    }

    report_append(buffer, capacity, &length,
                  "\nMEMORY-CARD HDD MODULES\n");
    for (port = 0; port < 2; port++) {
        report_append(buffer, capacity, &length,
                      "mc%u: %d module file(s) detected\n", port,
                      info->mc_module_count[port]);
        for (i = 0; i < sizeof(folders) / sizeof(folders[0]); i++) {
            if (info->mc_folder_mask[port] & (1u << i)) {
                unsigned int module;

                report_append(buffer, capacity, &length,
                              "  folder: %s\n", folders[i]);
                for (module = 0;
                     module < sizeof(modules) / sizeof(modules[0]);
                     module++) {
                    if (info->mc_folder_module_mask[port][i] &
                        (1u << module))
                        report_append(buffer, capacity, &length,
                                      "    %s\n", modules[module]);
                }
            }
        }
    }

    report_append(buffer, capacity, &length,
                  "\nDOWNSTREAM HDD EVIDENCE\n"
                  "__sysconf mount result: %d\n"
                  "__system mount result: %d\n"
                  "FHDB FREEHDB.CNF: %s\n"
                  "FHDB BOOT.ELF: %s\n"
                  "FHDB LK_Auto target: %s\n"
                  "OSDMBR.CNF: %s\n"
                  "OSDMBR boot_auto target: %s\n"
                  "OSDMBR boot_auto value: %s\n"
                  "PSBBN osdboot.elf: %s\n"
                  "PSBBN characteristic partitions: %d/8\n"
                  "HOSDMenu executable: %s\n"
                  "HDD-OSD osd100 executable: %s\n"
                  "Legacy osdmain.elf: %s\n\n",
                  info->sysconf_mount_result, info->system_mount_result,
                  info->fhdb_config ? info->fhdb_config_path : "not found",
                  info->fhdb_boot_elf ? "present" : "not found",
                  info->fhdb_auto_path[0] != '\0' ?
                      info->fhdb_auto_path : "unavailable",
                  info->osdmenu_mbr_config ? "present" : "not found",
                  info->osdmenu_auto_target == BOOT_AUTO_PSBBN ? "$PSBBN" :
                  info->osdmenu_auto_target == BOOT_AUTO_HOSDSYS ? "$HOSDSYS" :
                  info->osdmenu_auto_target == BOOT_AUTO_CUSTOM ? "custom" :
                                                                  "unavailable",
                  info->osdmenu_auto_path[0] != '\0' ?
                      info->osdmenu_auto_path : "unavailable",
                  info->psbbn_boot ? "present" : "not found",
                  info->psbbn_partition_count,
                  info->hosdmenu_boot ? "present" : "not found",
                  info->hddosd_boot ? info->hddosd_path : "not found",
                  info->legacy_osdmain ? "present" : "not found");

    report_append(buffer, capacity, &length, "ASSESSMENT\n");
    if (!info->pointer_consistent)
        report_append(buffer, capacity, &length,
                      "CRITICAL: osdStart/osdSize are inconsistent. Do not "
                      "attempt a payload restore until a header backup exists.\n");
    else if (start != 0 && info->payload_read_result < 0)
        report_append(buffer, capacity, &length,
                      "CRITICAL: The ROM pointer is enabled but the referenced "
                      "payload could not be read safely.\n");
    else if (start != 0 && info->payload_kelf_result < 0)
        report_append(buffer, capacity, &length,
                      "WARNING: The active sector image does not contain a "
                      "structurally valid KELF at its beginning.\n");
    else if (start != 0 && !info->fhdb_config && !info->psbbn_boot &&
             !info->hosdmenu_boot && !info->hddosd_boot &&
             !info->legacy_osdmain)
        report_append(buffer, capacity, &length,
                      "WARNING: A valid-looking active payload exists, but no "
                      "recognized downstream environment was found.\n");
    else
        report_append(buffer, capacity, &length,
                      "No structural contradiction was found in the observed "
                      "boot chain.\n");

    if ((info->mc_module_count[0] > 0 || info->mc_module_count[1] > 0) &&
        (info->skip_hdd[0] == 1 || info->skip_hdd[1] == 1))
        report_append(buffer, capacity, &length,
                      "NOTE: External HDD modules are present. Some FMCB setups "
                      "can load the HDD even when Skip_HDD is ON. Back up and "
                      "remove hddload.irx, dev9.irx, and atad.irx from the "
                      "active regional folder if HDD loading persists.\n");

    return length;
}
